services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    network_mode: host
    volumes:
      - ./:/home/node/app
    environment:
      - PLAYWRIGHT_MCP_CDP_ENDPOINT=http://localhost:9222

  # chrome:
  #   image: ghcr.io/browserless/chromium:latest
  #   ports:
  #     - "9222:9222"
  #   environment:
  #     - PORT=9222
  #     - CONNECTION_TIMEOUT=600000