services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    tty: true
    stdin_open: true
    environment:
      # - HTTP_PROXY=http://localhost:3128
      # - HTTPS_PROXY=http://localhost:3128
      - GOOGLE_CLOUD_PROJECT=
      - GOOGLE_CLOUD_LOCATION=
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/node/app
    # network_mode: "service:squid"

  chrome:
    image: ghcr.io/browserless/chromium:latest
    ports:
      - "9222:9222"
    environment:
      - PORT=9222
      - CONNECTION_TIMEOUT=600000

  # squid:
  #   image: ubuntu/squid
  #   volumes:
  #     - ./squid.conf:/etc/squid/squid.conf:ro