acl allowed_domains dstdomain .googleapis.com
acl allowed_domains dstdomain accounts.google.com
acl allowed_domains dstdomain .npmjs.org .npmjs.com
acl allowed_domains dstdomain .github.com .githubusercontent.com

http_access allow allowed_domains
http_access deny all
http_port 3128